swagger: '2.0'

#Basic information
info:
  version: 1.5.0-beta14
  title: Discourse REST API Specificatiom
  description: This specification describes the [Discourse](http://discourse.org) REST API and can be used to generate clients using the [Swagger](http://swagger.io) toolset.


#Meta types for API
produces:
  - application/json
consumes:
  - application/json


#Defines available security objects
securityDefinitions:
  api_username:
    name: api_username
    type: apiKey
    in: query
    description: Username of user making request
  api_key:
    name: api_key
    type: apiKey
    in: query
    description: Generated API key. Must have been generated for the username passed as `api_username`

#Defines default security objects for operations
security:
  - api_username: []
  - api_key: []


#List of operations available for the Discourse REST API
paths:

  #Request site information
  /site.json:
    get:
      operationId: getSiteInformation
      description: |
        Gets site information, including
        1. Categories
        2. Groups
        3. Post action types
        4. Topic flag types

        and many other properties related to how the Discourse site is set up
      
      security:
        - api_username: []
        - api_key: []
      
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Site'

#Definitions of types used in the REST calls (parameters and responses)
definitions:
  #The response for /site.json
  Site:
    properties:

      archetypes:
        description: Describes the available post archetypes
        type: array
        items:
          properties:
            id:
              type: string
            name:
              type: string
            options:
              type: array
              items:
                type: string

      default_archetype:
        description: The post archetype used by default
        type: string

      categories:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            color:
              type: string
            text_color:
              type: string
            slug:
              type: string
            topic_count:
              type: integer
            post_count:
              type: integer
            position:
              type: integer
            description:
              type: string
            description_text:
              type: string
            topic_url:
              type: string
            logo_url:
              type: string
            background_url:
              type: string
            read_restricted:
              type: boolean
            permission:
              type: integer
            notification_level:
              type: integer
            can_edit:
              type: boolean
            topic_template:
              type: string
            has_children:
              type: boolean        

      uncategorized_category_id:
        description: The category ID used for uncategorized posts
        type: integer

      notification_types:
        description: Map of string to integer listing the available notification types
        type: object
        additionalProperties:
          type: integer

      post_types:
        description: Map of string to integer listing the available post types
        type: object
        additionalProperties:
          type: integer

      groups:
        description: Lists the available groups
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string

      filters:
        description: Lists the available post filters (latest, new, unread etc.)
        type: array
        items:
          type: string

      periods:
        description: Lists the available time periods for filtering posts (all, yearly, daily etc.)
        type: array
        items:
          type: string

      top_menu_items:
        description: Lists the menu items shown at the top of the page for logged in users
        type: array
        items:
          type: string

      anonymous_top_menu_items:
        description: Lists the menu items shown at the top of the page for anonomous visitors
        type: array
        items:
          type: string

      is_readonly:
        description: Indicates whether the site is in read-only mode
        type: boolean

      disabled_plugins:
        description: Lists the plugins that are currently disabled
        type: array
        items:
          type: string

      suppressed_from_homepage_category_ids:
        description: Declares which categories are suppressed from the front page
        type: array
        items:
          type: integer

      post_action_types:
        description: Lists the actions users can apply to posts (like, bookmark, off_topic etc.)
        type: array
        items:
          type: object
          properties:
            name_key:
              type: string
            name:
              type: string
            description:
              type: string
            long_form:
              type: string
            is_flag:
              type: boolean
            icon:
              type: string
            id:
              type: integer
            is_custom_flag:
              type: boolean

      topic_flag_types:
        description: Lists the flags that can be applied to topics (inappropriate, spam etc.)
        type: array
        items:
          type: object
          properties:
            name_key:
              type: string
            name:
              type: string
            description:
              type: string
            long_form:
              type: string
            is_flag:
              type: boolean
            icon:
              type: string
            id:
              type: integer
            is_custom_flag:
              type: boolean

      trust_levels:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string

      user_fields:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            description:
              type: string
            field_type:
              type: string
            editable:
              type: boolean
            required:
              type: boolean
            show_on_profile:
              type: boolean
            position:
              type: integer
            options:
              description: Only available when 'field_type' is 'dropdown'
              type: array
              items:
                type: string

      user_field_max_length:
        type: integer
